### PR TITLE
upgrade to gray-matter 3

### PR DESCRIPTION
**Pull request by zeke**
Hey @jonschlinkert this PR upgrades gray-matter to version 3 with no other changes and it breaks some of the tests. Is this expected? What were the breaking changes for version 3?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
I think I know what's causing that. I bet it's b/c I made the `orig` property non-enumberable, but not `configurable`. A regression in gray-matter. I'll check and get that fixed, or figure out what the cause is if it's something else.

**Comment by zeke** [comment]
Thanks!

**Comment by jonschlinkert** [comment]
yep, that's what it was. 

In a future release I'll be removing `orig`. I wanted to this time but decided it would be better to do it after these changes. alas, I still managed to break gray-matter lol. fix coming up.

**Comment by jonschlinkert** [comment]
done. published and released as 3.0.2. I also pulled down `tree-hugger` again and run the tests, and everything is passing.

**Comment by zeke** [comment]
Sweet. Kicking off a new Travis build.

**Comment by zeke** [comment]
Didn't end up needing this functionality after all. Closing.

**Pull request closed without merging**
